title: Matti Pekkanen
description: PhD candidate at Aalto University. Research focus on mobile robotic mapping in dynamic environments and visual-language maps.
remote_theme: pages-themes/leap-day@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


#remote_theme: pages-themes/cayman@v0.2.0